version: '3.7'
services:
  genie-client:
    image: jaxzin/genie-client:0.0.1
    build: .
    container_name: genie-client
    restart: unless-stopped
    environment:
      XDG_RUNTIME_DIR: /run/user/1000
      DBUS_SESSION_BUS_ADDRESS: 'unix:path=/run/user/1000/bus'
      ACCESS_TOKEN: ${GENIE_ACCESS_TOKEN}
    devices:
      - /dev/snd
    volumes:
      - /run/user/1000/bus
    ports:
      - '8000:8000'
