version: '3.7'
services:
  genie-client:
    image: jaxzin/genie-client:0.0.1
    build: .
    container_name: genie-client
    restart: unless-stopped
    environment:
      XDG_RUNTIME_DIR: /run/user/1000
      DBUS_SESSION_BUS_ADDRESS: 'unix:path=/run/user/1000/bus'
      ACCESS_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MTE3YzllYWJkNTc5ZDQ2IiwiYXVkIjoib2F1dGgyIiwic2NvcGUiOlsicHJvZmlsZSIsInVzZXItcmVhZCIsInVzZXItcmVhZC1yZXN1bHRzIiwidXNlci1leGVjLWNvbW1hbmQiLCJ1c2VyLXN5bmMiLCJkZXZlbG9wZXItcmVhZCIsImRldmVsb3Blci11cGxvYWQiLCJkZXZlbG9wZXItYWRtaW4iXSwiaWF0IjoxNjQwNjY1NTY0LCJleHAiOjE2NDMyNTc1NjR9.J0KNFWidVXSmwsRalUqCXYGTTHKHTk61r5K0bOGzfiA
    devices:
      - /dev/snd
    volumes:
      - /run/user/1000/bus
    ports:
      - '8000:8000'
